### ISSUE TITLE
IOerror

### ISSUE THREAD

**Issue by vinodrajendran001** [FrederikDiehl/apsis#130]
I just ran the breze mnist example and I got the following error

/home/vinod/anaconda2/bin/python /home/vinod/Downloads/MLPonTheano/apsis_mnist.py
gnumpy: failed to import cudamat. Using npmat instead. No GPU will be used.
warning in stationary: failed to import cython module: falling back to numpy
Traceback (most recent call last):
  File "/home/vinod/Downloads/MLPonTheano/apsis_mnist.py", line 214, in <module>
    demo_on_MNIST(10, 30, 5)
  File "/home/vinod/Downloads/MLPonTheano/apsis_mnist.py", line 196, in demo_on_MNIST
    do_evaluation(LAss, "random_mnist", X, Z, VX, VZ)
  File "/home/vinod/Downloads/MLPonTheano/apsis_mnist.py", line 150, in do_evaluation
    to_eval = LAss.get_next_candidate(opt)
  File "/home/vinod/anaconda2/lib/python2.7/site-packages/apsis/assistants/lab_assistant.py", line 646, in get_next_candidate
1.28746032715e-05	Beginning with random initialization. Step 0/50
    num_min_finished = len(self._exp_assistants[exp_id][0]._experiment.candidates_finished) + len(self.candidates_pending[exp_id][0])
KeyError: 'random_mnist'
Process Process-8:
Traceback (most recent call last):
  File "/home/vinod/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/vinod/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vinod/anaconda2/lib/python2.7/site-packages/apsis/optimizers/optimizer.py", line 382, in dispatch_queue_backend
    optimizer.run()
  File "/home/vinod/anaconda2/lib/python2.7/site-packages/apsis/optimizers/optimizer.py", line 320, in run
    self._check_generation()
  File "/home/vinod/anaconda2/lib/python2.7/site-packages/apsis/optimizers/optimizer.py", line 367, in _check_generation
    if (self._out_queue.empty() or
  File "<string>", line 2, in empty
  File "/home/vinod/anaconda2/lib/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe
Process Process-10:
Traceback (most recent call last):
  File "/home/vinod/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/vinod/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vinod/anaconda2/lib/python2.7/site-packages/apsis/optimizers/optimizer.py", line 382, in dispatch_queue_backend
    optimizer.run()
  File "/home/vinod/anaconda2/lib/python2.7/site-packages/apsis/optimizers/optimizer.py", line 320, in run
    self._check_generation()
  File "/home/vinod/anaconda2/lib/python2.7/site-packages/apsis/optimizers/optimizer.py", line 367, in _check_generation
    if (self._out_queue.empty() or
  File "<string>", line 2, in empty
  File "/home/vinod/anaconda2/lib/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe
Process Process-4:
Traceback (most recent call last):
  File "/home/vinod/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/vinod/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vinod/anaconda2/lib/python2.7/site-packages/apsis/optimizers/optimizer.py", line 382, in dispatch_queue_backend
    optimizer.run()
  File "/home/vinod/anaconda2/lib/python2.7/site-packages/apsis/optimizers/optimizer.py", line 320, in run
    self._check_generation()
  File "/home/vinod/anaconda2/lib/python2.7/site-packages/apsis/optimizers/optimizer.py", line 367, in _check_generation
    if (self._out_queue.empty() or
  File "<string>", line 2, in empty
  File "/home/vinod/anaconda2/lib/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe
Process Process-2:
Traceback (most recent call last):
  File "/home/vinod/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/vinod/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vinod/anaconda2/lib/python2.7/site-packages/apsis/optimizers/optimizer.py", line 382, in dispatch_queue_backend
    optimizer.run()
  File "/home/vinod/anaconda2/lib/python2.7/site-packages/apsis/optimizers/optimizer.py", line 320, in run
    self._check_generation()
  File "/home/vinod/anaconda2/lib/python2.7/site-packages/apsis/optimizers/optimizer.py", line 367, in _check_generation
    if (self._out_queue.empty() or
  File "<string>", line 2, in empty
  File "/home/vinod/anaconda2/lib/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe
Process Process-6:
Traceback (most recent call last):
  File "/home/vinod/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/vinod/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vinod/anaconda2/lib/python2.7/site-packages/apsis/optimizers/optimizer.py", line 382, in dispatch_queue_backend
    optimizer.run()
  File "/home/vinod/anaconda2/lib/python2.7/site-packages/apsis/optimizers/optimizer.py", line 320, in run
    self._check_generation()
  File "/home/vinod/anaconda2/lib/python2.7/site-packages/apsis/optimizers/optimizer.py", line 367, in _check_generation
    if (self._out_queue.empty() or
  File "<string>", line 2, in empty
  File "/home/vinod/anaconda2/lib/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe

Process finished with exit code 1

**Comment by FrederikDiehl** [comment]
First, the actual relevant part is this:

    File "/home/vinod/Downloads/MLPonTheano/apsis_mnist.py", line 214, in demo_on_MNIST(10, 30, 5)
    File "/home/vinod/Downloads/MLPonTheano/apsis_mnist.py", line 196, in demo_on_MNIST
    do_evaluation(LAss, "random_mnist", X, Z, VX, VZ)
    File "/home/vinod/Downloads/MLPonTheano/apsis_mnist.py", line 150, in do_evaluation
    to_eval = LAss.get_next_candidate(opt)
    File "/home/vinod/anaconda2/lib/python2.7/site-packages/apsis/assistants/lab_assistant.py", line 646, in get_next_candidate
    1.28746032715e-05 Beginning with random initialization. Step 0/50
    num_min_finished = len(self._exp_assistants[exp_id][0]._experiment.candidates_finished) + len(self.candidates_pending[exp_id][0])
    KeyError: 'random_mnist'

Generally, the issue is that you seem to run a demo (with the new architecture, see the conn.send stuff) that has been written for the old architecture. With commit 0006022 I've deleted all of them (for different reasons; noise wasn't useful for the user; I didn't want the MNIST example to depend on breze, etc), before merging it into master. Updating from master should fix the problem (via the simple solution of the demo no longer existing).
Once done, can you run demo_branin.py in demos?
That is, run (in one terminal):

    python [APSIS]/code/apsis/webservice/REST_start_script.py
And in another

    python [APSIS]/code/apsis/demos/demo_branin.py
The first terminal should, after a time, display WARNING: reconstraining parameters GP_regression several times, the other 

    Connecting to http://localhost:5000
    Initialized all optimizers.
    finished 10
    finished 20
    finished 30
    finished 40
Additionally, you should then be able to see both experiments at localhost:5000 in your browser.

**Comment by vinodrajendran001** [comment]
Actually I need to run the experiment on breze. I 'll try to modify this code according to the new architecture of apsis.

**Comment by FrederikDiehl** [comment]
For this, it's probably best to start define the parameter definitions as something like a kwarg dictionary.
For example, 

    param_defs = {
        "p_dropout_hiddens": {"type": "MinMaxNumericParamDef", "lower_bound": 0, "upper_bound": 1},
        "p_dropout_inpt": {"type": "MinMaxNumericParamDef", "lower_bound": 0, "upper_bound": 1},
        [....]
    }

Then, you can simply feed the candidate parameter dictionary into your model definition, for example

    to_eval = conn.get_next_candidate(exp_id)
    model = DropoutMlp(**to_eval["params"])

    for i, info in enumerate(model.powerfit((X, Z), (vX, vZ), 
                                          stop, pause)):
        row = '%(n_iter)i\t%(loss)s\t%(val_loss)s\t' % info
        print row    
    to_eval["result"] =  info["val_loss"]
    conn.update(exp_id, to_eval, "finished")

I have not actually tested the code (and you have to define stop and pause criteria, for example), but it should probably work, or be easily modified to work.

**Comment by vinodrajendran001** [comment]
I have time limitations for running a job, so I want to save the parameters of LAss(ValidationLabAssistant) and restore it.

How can I do this ?

**Comment by FrederikDiehl** [comment]
I currently haven't implemented functionality to directly store and load the state of a LabAssistant. It's on my ToDos, though.
For now, you can use the get_candidates functionality to receive the state of any experiment (as a list of finished, pending and working candidates). Store this list somewhere on stopping the LAss.
Then, when you want to resume the optimization process, start a new LabAssistant with the same parameters and manually create candidates with the evaluated parameter values and results. Then you can just call update with status=finished for each of them and you should receive a reconstruction LabAssistant.

That being said, I think ValidationLabAssistant is probably the wrong Assistant for you, as it's built to evaluate and compare the performance of optimizers. Since your goal is simply to optimize breze parameters, the normal LabAssistant should work nicely.

**Comment by vinodrajendran001** [comment]
According to your example i.e demo_branin.py you have two parameters 'x' and 'y' , so you  used branin_func, but what about more than 2 parameters ?

Because In my case I have 4 parameters.

**Comment by FrederikDiehl** [comment]
There are two ways. One is to define a `train_breze(param1, param2, param3, param4)` function which you then feed the four extracted parameters to. Then, call something like
    
    to_eval = conn.get_next_candidate(exp_id)
    result = branin_func(to_eval["params"]["param1"], to_eval["params"]["param2"], to_eval["params"]["param3"], to_eval["params"]["param4"])

Of course, that's pretty bad style (unless you need it). Therefore, I recommend using it as a kwarg field. So, call each parameter the name it has in the initialization, and simply do

     to_eval = conn.get_next_candidate(exp_id)
    result = branin_func(**to_eval["params"])

**Comment by vinodrajendran001** [comment]
Actually previously I tried first way, but if you notice branin_func has only 2 parameters (x,y)
'''
def branin_func(x, y, a=1, b=5.1/(4*math.pi**2), c=5/math.pi, r=6, s=10,
                t=1/(8*math.pi)):
'''
So thats why I asked you this question.

**Comment by FrederikDiehl** [comment]
Yes, branin_func has only two parameters we want to optimize, which are called x and y here. The other parameters control the shape of the function itself, and are by default chosen as on http://www.sfu.ca/~ssurjano/branin.html (where they are called x_1 and x_2).
Again, you can easily change the number of parameters you want to optimize depending on your function.

(I may not have understood your question correctly; could you reformulate it?)
